apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
  labels:
    type: frontend
    name: my-app
spec:
  #completion creates 3 pods sequentially, 2nd pod is created after 1st is finished successfully. For error cases, it creates pod  as long as the completion count is not met
  completions: 3
  parallelism: 3 #to create pods parallely 
  template:
    spec:
      containers:
        - name: math-add
          image: ubuntu
          command: ['expr', '3', '+', '2']
      restartPolicy: Never